### ISSUE TITLE
LDAP integration

### ISSUE THREAD

**Issue by stvdo** [i2group/analyze-deployment#5]
**Describe the bug**
I would like to link i2 Analyze to a local LDAP provider with is running in another Docker container. But somehow the old basic user is still active. What do I do wrong?

**To Reproduce**
1. I create an LDAP container in docker
```
version: '3.8'
services:
  ldap:
    image: osixia/openldap:latest
    container_name: ldap_server
    environment:
      LDAP_ORGANISATION: "Company EIA Network"
      LDAP_DOMAIN: "company.eia"
      LDAP_ADMIN_PASSWORD: "admin"
    ports:
      - "389:389" # LDAP port
      - "636:636" # LDAPS port
    networks:
      - eia
    volumes:
      - ldap_data:/var/lib/ldap
      - ldap_config:/etc/ldap/slapd.d

networks:
  eia:
    driver: bridge

volumes:
  ldap_data:
  ldap_config:
```
With the users
```
# Organizational Unit: Employees
dn: ou=employees,dc=company,dc=eia
objectClass: organizationalUnit
ou: employees

# Organizational Unit: Groups
dn: ou=groups,dc=company,dc=eia
objectClass: organizationalUnit
ou: groups

# Group: Analyst
dn: cn=Analyst,ou=groups,dc=company,dc=eia
objectClass: groupOfNames
cn: Analyst
member: cn=John Doe,ou=employees,dc=company,dc=eia

# Group: Administrator
dn: cn=Administrator,ou=groups,dc=company,dc=eia
objectClass: groupOfNames
cn: Administrator
member: cn=Jane Smith,ou=employees,dc=company,dc=eia

# User: John Doe
dn: cn=John Doe,ou=employees,dc=company,dc=eia
objectClass: inetOrgPerson
cn: John Doe
sn: Doe
uid: jdoe
mail: jdoe@company.eia
userPassword: password

# User: Jane Smith
dn: cn=Jane Smith,ou=employees,dc=company,dc=eia
objectClass: inetOrgPerson
cn: Jane Smith
sn: Smith
uid: jsmith
mail: jsmith@company.eia
userPassword: password
```
The container is running in the eia network
![image](https://github.com/user-attachments/assets/e79b30bf-0f45-4aff-b4d5-0cffe3b182e1)

3. I added 2 features to the server.extensions.xml
     <feature>appSecurity-2.0</feature>
    <feature>ldapRegistry-3.0</feature>
4. I added the code below to user.registry.xml and removed the basicRegistry
```
 <ldapRegistry id="LDAP" realm="LDAPRealm">
    <!-- Replace with your LDAP server details -->
    <ldapServer host="localhost" port="389" sslEnabled="false" />
    
    <!-- Base Distinguished Name (DN) for LDAP -->
    <baseDN>dc=company,dc=eia</baseDN>
    
    <!-- Bind Distinguished Name (DN) and password for authentication -->
    <bindDN>cn=admin,dc=company,dc=eia</bindDN>
    <bindPassword>admin</bindPassword>
    
    <!-- Filter to retrieve users -->
    <userFilter>(uid=%v)</userFilter>
    
    <!-- Filter to retrieve groups -->
    <groupFilter>(member=%v)</groupFilter>
  </ldapRegistry>
```
5. I deployed the my config succesfully 
![image](https://github.com/user-attachments/assets/166fba13-78da-4ba4-829f-409b1b64bcab)

**Expected behavior**
I expect that I can login with Johns or Janes login in i2 Analzye. But I am automatically logged in as Steven (my disabled basic user).

![image](https://github.com/user-attachments/assets/1fa308c6-67cc-4cdc-afc6-2aaa0d9d2cab)

![image](https://github.com/user-attachments/assets/750c2380-cf84-4395-be44-7f036a3d266f)

**Hardware and Software information**
 - OS: Windows
 - Version: 3.0.1
 - i2 Analyze version: 4.4.4
